config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  namespace :api, defaults: { format: :json } do 
    resources :journals, only: [:index, :show, :create, :destroy]
    resources :chapters, only: [:show, :create, :update, :destroy]
    resources :stories, only: [:index, :create, :update, :destroy]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  fname           :string(255)
#  lname           :string(255)
#

class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, uniqueness: true
  
  has_many :journals
  has_many :backgrounds
  
  attr_reader :password
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user && user.is_password?(user_params[:password]) ? user : nil
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save! ; self.session_token
  end
  
  private
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_current_user
  
  def new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.update_attributes(user_params)
      login!(@user)
      assign_background
      redirect_to root_url
    else
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="minimal-wrapper">
  <div class="bar-header"></div>
  
  <div class="minimal-brand-frame">
    <div class="branding">
      <h1><a href='/'>Annotate</a></h1>
      
      <%= image_tag(("feather-small.gif"), class: "brand-image") %>
      
      <h2>Create User</h2>
    </div>
  </div>

  <div class="minimal-login-wrapper">
    <div class="signin">
      <%= render "shared/login", action: users_url, button: "Create User", guest: false%>
    </div>
  </div>
  
  <div class="content-switch">
    <p>Already have an account?</p>
      <%= link_to "Sign In", new_session_url %>
  </div>
</div>