config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  namespace :api, defaults: { format: :json } do 
    resources :journals, only: [:index, :show, :create, :destroy]
    resources :chapters, only: [:show, :create, :update, :destroy]
    resources :stories, only: [:index, :create, :update, :destroy]
  end
end

app/views/shared/_errors.html.erb
<% if flash[:notice] %>
  <ul>
    <% flash[:notice].each do |notice| %>
      <li><%= notice %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button 
        type="button" 
        class="navbar-toggle" 
        data-toggle="collapse" data-target="#navbar-brand-centered">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#">
        <div class="navbar-brand navbar-brand-centered">
          <img src="/assets/feather-small.gif" class='header-brand-image'>
          Annotate
        </div>
      </a>
    </div>
    
    <div class="collapse navbar-collapse" id="navbar-brand-centered">
      <ul class="nav navbar-nav" id='current-journal-menu-pos'>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" 
             class="dropdown-toggle new-board-header-link"
             data-toggle="dropdown">
               <span class="glyphicon glyphicon-plus"></span>
          </a>
          <ul class="dropdown-menu">
            <li class='dropdown'>
              <a href="#"
                 class="dropwdown-toggle new-journal-header-button">
                 New Journal
              </a>
            </li>
          </ul>
        </li>
        
        <li class='gravatar-img'>
          <%= gravatar_image_tag(current_user.email, alt: 'John') %>
        </li>
        
        <li class="dropdown">
          <a 
            href="#" 
            class="dropdown-toggle" 
            data-toggle="dropdown">
            <%= current_user.fname %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <!-- <li>
              <a href="#"
                 id='change-background-button'>Change Background</a>
            </li>

            <li><a href="#">Update Name</a></li>
            <li class="divider"></li> -->
            <li><%= link_to 'Sign Out', session_url, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
<nav>

app/views/shared/_login.html.erb
<form id="login-form" action="<%= action %>" method="POST">
  <%= auth_token %>
  
  <div class="form-group">
    <label for="email">Email Address</label>
    <input type="text" name="user[email]" id="email"></input>
  </div>
  
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="user[password]" id="password"></input>
  </div>
  
  <input 
    type="submit" 
    class="btn btn-primary login-button" 
    id="login" 
    value="<%= button %>">
  
  <% if guest %>  
    <input 
      type="submit" 
      class="btn btn-primary login-button"
      id="demo-user-login" 
      value="Guest Login">
  <% end %>
</form>